http:
  port: "8081"
  
https:
  port: "8082"
  
  
db:
  host: "mulesoft-1.ceogjq7zewy5.us-east-1.rds.amazonaws.com"
  port: "3306"
  user: "admin"
  password: "![I0znQ/9ceTn29wX+jhn2rA==]"
  database: "mulesoft"